version: 1
formatters:
  simple:
    format: '%(asctime)s | %(name)-30s | %(levelname)-8s | #%(lineno)-5d| %(message)s'
  colored:
    (): colorlog.ColoredFormatter
    format: '%(asctime)s | %(name)-30s | %(log_color)s%(levelname)-8s | #%(lineno)-5d| %(blue)s%(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: colored
    stream: ext://sys.stdout
  out:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  file_handler:
    class: logging.FileHandler
    level: DEBUG
    formatter: simple
    filename: _
    encoding: utf8
    mode: a
root:
  level: DEBUG
  handlers:
    - console
disable_existing_loggers: false